#!/bin/bash

#===============================================================
# Script: ad_group
# Syntax: ad_group <hostname> [-h]
# Description: Tree view of client Centrify role members
# Option: hostname|Hostname
# Option: -h, --help|Display help
#===============================================================

set -e
set -u
set -o pipefail

CENTRIFY_TOOLS_CONF=${CENTRIFY_TOOLS_CONF:=default}

if [ ! -f /etc/centrify_tools/${CENTRIFY_TOOLS_CONF}.conf ]
then
	echo "AD Config file : /etc/centrify_tools/${CENTRIFY_TOOLS_CONF}.conf is not found"
	exit 1
fi
source /etc/centrify_tools/${CENTRIFY_TOOLS_CONF}.conf
source /usr/lib/ad_functions

help() {
    echo "Usage: `basename $0` [-h|--help] <ad group>"
    exit 0
}

[ $# -eq 0 ] && help
[ "$1" = "-h" -o "$1" = "--help" ] && help
check_kerberos
group_tree "$1"
