#!/bin/bash

#===============================================================
# Script: ad_zones
# Syntax: ad_zones [-h]
# Description: List all Centrify zones
# Option: -h, --help|Display help
#===============================================================

set -e
set -u
set -o pipefail

CENTRIFY_TOOLS_CONF=${CENTRIFY_TOOLS_CONF:=default}

if [ ! -f /etc/centrify_tools/${CENTRIFY_TOOLS_CONF}.conf ]
then
        echo "AD Config file : /etc/centrify_tools/${CENTRIFY_TOOLS_CONF}.conf is not found"
        exit 1
fi
source /etc/centrify_tools/${CENTRIFY_TOOLS_CONF}.conf
source /usr/lib/ad_functions

help() {
    echo "Usage: `basename $0` [-h|--help]"
    exit 0
}

[ $# -ne 0 ] && [ "$1" = "-h" -o "$1" = "--help" ] && help
check_kerberos

ldap_query "$LDAP_ZONE_BASE" "one" "" "cn" | grep cn: | sed 's/cn: //'
