#!/bin/bash

#===============================================================
# Script: zone_role_tree
# Syntax: zone_role_tree <zone> [-h]
# Description: Tree view of zone Centrify role members
# Option: zone|Zone
# Option: -h, --help|Display help
#===============================================================

set -e
set -u
set -o pipefail

CENTRIFY_TOOLS_CONF=${CENTRIFY_TOOLS_CONF:=default}

if [ ! -f /etc/centrify_tools/${CENTRIFY_TOOLS_CONF}.conf ]
then
        echo "AD Config file : /etc/centrify_tools/${CENTRIFY_TOOLS_CONF}.conf is not found"
        exit 1
fi
source /etc/centrify_tools/${CENTRIFY_TOOLS_CONF}.conf
source /usr/lib/ad_functions

help() {
    echo "Usage: `basename $0` [-h|--help] <zone>"
    exit 0
}

[ $# -eq 0 ] && help
[ "$1" = "-h" -o "$1" = "--help" ] && help
check_kerberos
zone_role_tree "$1"
